// lib/conditions-data.ts
// Fonte única de verdade para todas as distrofias e seus subtipos.
// Condições com subtypes[] recebem uma subpágina própria em /distrofias/[slug].

export interface Subtype {
  id: string;
  name: string;
  badge: string;
  inheritancePattern: string;
  affectedGene: string;
  severity: 'leve' | 'moderada' | 'grave' | 'variável';
  description: string;
  details: string;
  symptoms: string[];
  care: string;
}

export interface Condition {
  id: string;          // também usado como slug na URL
  name: string;
  badge: string;
  frequencyRank: number; // 1 (rara) → 5 (mais frequente)
  frequencyLabel: string;
  inheritancePattern: string;
  affectedGene: string;
  description: string;
  details: string;
  symptoms: string[];
  care: string;
  hasSubtypes: boolean;
  subtypes?: Subtype[];
}

export const conditions: Condition[] = [
  {
    id: 'duchenne',
    name: 'Distrofia de Duchenne (DMD)',
    badge: '★ A mais frequente na infância',
    frequencyRank: 5,
    frequencyLabel: '1 em cada 3.500 meninos nascidos vivos',
    inheritancePattern: 'Ligada ao cromossomo X (recessiva)',
    affectedGene: 'Gene DMD (cromossomo X) — ausência quase total de distrofina',
    description: 'A forma mais comum e grave de distrofia muscular na infância. A ausência da proteína distrofina leva à degeneração muscular progressiva a partir dos primeiros anos de vida.',
    details: 'Afeta predominantemente meninos. Os primeiros sinais surgem entre 2 e 5 anos. Com o avanço, há perda progressiva da marcha (geralmente entre 9 e 12 anos) e comprometimento cardiorrespiratório nas fases tardias. O diagnóstico precoce é fundamental para iniciar corticoterapia e avaliar elegibilidade a terapias inovadoras como salto de éxon e terapia gênica.',
    symptoms: [
      'Sinal de Gowers: apoio nas próprias pernas para levantar do chão',
      'Hipertrofia de panturrilhas (pseudohipertrofia)',
      'Quedas frequentes e dificuldade para correr ou subir escadas',
      'Marcha anserina (andar bamboleante, na ponta dos pés)',
      'Escoliose progressiva após perda da marcha',
      'Comprometimento cardíaco e respiratório nas fases avançadas',
    ],
    care: 'Corticoterapia precoce (deflazacort ou prednisona), fisioterapia respiratória e motora, cardiologia preventiva, ventilação não invasiva, e avaliação para terapias de precisão (salto de éxon, atalureno, terapia gênica).',
    hasSubtypes: false,
  },

  {
    id: 'miotonica-dm1',
    name: 'Distrofia Miotônica tipo 1 (DM1 / Steinert)',
    badge: '★ A mais comum em adultos',
    frequencyRank: 5,
    frequencyLabel: '1 em cada 8.000 pessoas — a mais comum em adultos',
    inheritancePattern: 'Autossômica dominante',
    affectedGene: 'Gene DMPK (cromossomo 19) — expansão de repetições CTG',
    description: 'A forma mais prevalente de distrofia muscular em adultos. Afeta não só os músculos, mas também coração, pulmão, olhos, sistema hormonal e cognitivo — é uma doença multissistêmica.',
    details: 'A DM1 varia enormemente em gravidade — de formas congênitas graves a formas levíssimas em adultos idosos. A miotonia (dificuldade de relaxar o músculo após contração) é um sinal clássico. O comprometimento cardíaco com arritmias e bloqueios exige monitoramento rigoroso, pois é a principal causa de morte súbita.',
    symptoms: [
      'Miotonia: dificuldade de relaxar a mão após apertar algo',
      'Fraqueza distal (face, pescoço, mãos e pés afetados primeiro)',
      'Ptose palpebral e face inexpressiva',
      'Catarata precoce',
      'Arritmias cardíacas e bloqueios de condução',
      'Sonolência excessiva e comprometimento cognitivo em formas graves',
    ],
    care: 'ECG e Holter anual (ou semestral), pneumologia, tratamento de catarata, acompanhamento neurológico e endocrinológico. Mexiletina pode reduzir a miotonia. Fisioterapia motora e respiratória.',
    hasSubtypes: false,
  },

  {
    id: 'fshd',
    name: 'Fácio-Escápulo-Umeral (FSHD)',
    badge: '3ª mais frequente globalmente',
    frequencyRank: 4,
    frequencyLabel: '1 em cada 7.500 a 20.000 pessoas',
    inheritancePattern: 'Autossômica dominante',
    affectedGene: 'D4Z4 (cromossomo 4q35) — FSHD1 | Gene SMCHD1 — FSHD2',
    description: 'Compromete a musculatura do rosto, dos ombros e dos braços. A progressão é altamente variável — há casos leves sem necessidade de cadeira de rodas e casos graves com comprometimento precoce.',
    details: 'A FSHD afeta homens e mulheres igualmente, embora homens apresentem formas geralmente mais graves. Um traço marcante é a assimetria — um lado do corpo pode ser muito mais afetado. A variação dentro de uma mesma família pode ser enorme.',
    symptoms: [
      'Escápulas aladas (saliência visível do osso da omoplata)',
      'Dificuldade para assobiar, sorrir ou fechar os olhos completamente',
      'Fraqueza nos braços e ombros — dificuldade de levantar os braços',
      'Fraqueza nos membros inferiores em estágios avançados (até 20% dos casos)',
      'Perda auditiva de alta frequência em formas mais graves',
    ],
    care: 'Fisioterapia para estabilização postural e escápula, órteses para pé caído, acompanhamento ortopédico. Losmapimod em ensaios clínicos como terapia-alvo.',
    hasSubtypes: true,
    subtypes: [
      {
        id: 'fshd1',
        name: 'FSHD tipo 1 (FSHD1)',
        badge: 'Mais comum — ~95% dos casos',
        inheritancePattern: 'Autossômica dominante',
        affectedGene: 'Deleção de unidades D4Z4 no cromossomo 4q35 (≤8 unidades)',
        severity: 'variável',
        description: 'Forma mais frequente da FSHD, causada pela redução no número de repetições da sequência D4Z4, levando à expressão aberrante do gene DUX4.',
        details: 'Quanto menor o número de repetições D4Z4 restantes (tamanho do fragmento EcoRI), mais grave tende a ser a doença. Com 1–3 unidades, a forma é geralmente grave e de início precoce. Com 7–8 unidades, a progressão costuma ser muito lenta. O diagnóstico é feito por teste genético específico de Southern blot.',
        symptoms: [
          'Fraqueza facial (dificuldade de assobiar, soprar velas, sorrir)',
          'Escápulas aladas — sinal mais característico',
          'Fraqueza nos braços (especialmente bíceps e tríceps)',
          'Fraqueza abdominal (sinal de Beevor — umbigo sobe ao levantar a cabeça)',
          'Fraqueza nos membros inferiores em estágios avançados',
        ],
        care: 'Fisioterapia para fortalecer musculatura escapular e core, estabilização escapular cirúrgica em casos selecionados, órteses para pé caído, monitoramento auditivo e oftalmológico.',
      },
      {
        id: 'fshd2',
        name: 'FSHD tipo 2 (FSHD2)',
        badge: 'Rara — ~5% dos casos',
        inheritancePattern: 'Autossômica dominante (digênica)',
        affectedGene: 'Gene SMCHD1 (cromossomo 18) + alelo permissivo em 4q35',
        severity: 'variável',
        description: 'Forma menos comum, fenotipicamente idêntica à FSHD1, mas causada por variantes no gene SMCHD1 combinadas com um alelo permissivo no cromossomo 4. Requer testes genéticos específicos para diferenciação.',
        details: 'A FSHD2 tem o mesmo quadro clínico da FSHD1, mas a causa genética é diferente — variantes patogênicas no gene SMCHD1 (que normalmente silencia a região D4Z4) em combinação com número normal de repetições D4Z4 em um alelo permissivo. O diagnóstico costuma ser mais difícil por não ser detectada pelo teste padrão de Southern blot da FSHD1.',
        symptoms: [
          'Clinicamente idêntica à FSHD1',
          'Fraqueza facial progressiva',
          'Escápulas aladas bilaterais',
          'Fraqueza proximal nos braços e ocasionalmente nas pernas',
        ],
        care: 'Idêntico à FSHD1. O diagnóstico correto é importante para o aconselhamento genético familiar, pois a herança é digênica.',
      },
    ],
  },

  {
    id: 'becker',
    name: 'Distrofia de Becker (BMD)',
    badge: 'Variante mais branda da DMD',
    frequencyRank: 4,
    frequencyLabel: '1 em cada 18.500 meninos',
    inheritancePattern: 'Ligada ao cromossomo X (recessiva)',
    affectedGene: 'Gene DMD (cromossomo X) — distrofina parcialmente funcional',
    description: 'A distrofina é produzida em quantidade reduzida ou com função parcial. A progressão é mais lenta que a Duchenne e os sintomas podem surgir da infância até a vida adulta avançada.',
    details: 'Alguns portadores de BMD têm sintomas tão leves que só são diagnosticados por acaso. O coração é frequentemente afetado antes dos músculos esqueléticos — cardiomiopatia dilatada é a principal causa de mortalidade na BMD e pode ocorrer mesmo em pacientes que caminham normalmente.',
    symptoms: [
      'Cãibras intensas durante ou após exercício físico',
      'Fadiga muscular e dificuldade para subir escadas',
      'Fraqueza muscular proximal de início tardio',
      'Cardiomiopatia dilatada (muitas vezes o primeiro sintoma grave)',
      'Hipertrofia de panturrilhas',
    ],
    care: 'Ecocardiograma e ECG periódicos, inibidores da ECA ou betabloqueadores se houver cardiomiopatia, reabilitação preventiva e orientação sobre exercícios.',
    hasSubtypes: false,
  },

  {
    id: 'miotonica-dm2',
    name: 'Distrofia Miotônica tipo 2 (DM2 / PROMM)',
    badge: 'Forma proximal da Miotônica',
    frequencyRank: 3,
    frequencyLabel: 'Prevalência variável — provavelmente subdiagnosticada',
    inheritancePattern: 'Autossômica dominante',
    affectedGene: 'Gene CNBP (cromossomo 3) — expansão de repetições CCTG',
    description: 'Forma mais branda que a DM1, com fraqueza muscular proximal (quadril e coxas), miotonia e comprometimento multissistêmico mais leve. A dor muscular intensa é uma característica marcante.',
    details: 'A DM2 muitas vezes é confundida com polimiosite ou outras miopatias por conta da fraqueza proximal. Diferente da DM1, raramente apresenta forma congênita grave. É provavelmente subdiagnosticada pela variabilidade clínica e por necessitar de teste genético específico (expansão CCTG grande demais para PCR convencional).',
    symptoms: [
      'Fraqueza nos quadris e coxas (dificuldade de levantar de cadeira)',
      'Miotonia mais branda que na DM1',
      'Dor muscular (mialgia) frequentemente intensa — sinal característico',
      'Catarata precoce',
      'Arritmias cardíacas',
    ],
    care: 'Monitoramento cardíaco, fisioterapia, avaliação oftalmológica para catarata. Manejo da dor com analgésicos e, se miotonia sintomática, mexiletina.',
    hasSubtypes: false,
  },

  {
    id: 'lgmd',
    name: 'Cintura Escapular e Pélvica (LGMD)',
    badge: 'Mais de 30 subtipos descritos',
    frequencyRank: 3,
    frequencyLabel: '1 em cada 14.500 a 123.000 (varia por subtipo)',
    inheritancePattern: 'Autossômica dominante (LGMD D) ou recessiva (LGMD R)',
    affectedGene: 'CAPN3, DYSF, SGCA/B/C/D, FKRP, ANO5, LAMA2 entre outros',
    description: 'Grupo diverso de distrofias que compromete principalmente a musculatura dos ombros e do quadril. A gravidade e a progressão dependem muito do subtipo genético específico.',
    details: 'Com mais de 30 subtipos identificados, as LGMDs têm prognósticos muito diferentes entre si. O diagnóstico por painel genético é essencial para orientar prognóstico, acompanhamento e acesso a ensaios clínicos.',
    symptoms: [
      'Dificuldade para levantar os braços acima da cabeça',
      'Dificuldade para levantar de uma cadeira sem apoio das mãos',
      'Marcha anserina em estágios avançados',
      'Contraturas articulares',
      'Comprometimento cardíaco e respiratório em subtipos específicos',
    ],
    care: 'Painel genético de nova geração, fisioterapia, acompanhamento cardiológico e pneumológico conforme subtipo.',
    hasSubtypes: true,
    subtypes: [
      {
        id: 'lgmd-r1',
        name: 'LGMD R1 — Calpainopatia',
        badge: 'Mais comum entre as LGMD',
        inheritancePattern: 'Autossômica recessiva',
        affectedGene: 'Gene CAPN3 (cromossomo 15)',
        severity: 'variável',
        description: 'A forma recessiva mais frequente de LGMD em muitas populações. Afeta a calpaína-3, uma protease muscular essencial.',
        details: 'A progressão é variável — alguns pacientes perdem a marcha na 3ª–4ª décadas enquanto outros mantêm por mais tempo. O comprometimento cardíaco não é típico, mas a escoliose é comum. A CK sérica costuma ser bastante elevada.',
        symptoms: ['Fraqueza nos músculos do quadril e ombros', 'Elevação importante da CK', 'Escoliose progressiva', 'Contraturas de tornozelos em estágios avançados'],
        care: 'Fisioterapia, ortopedia para escoliose, órteses se necessário. Ensaios de terapia gênica em andamento.',
      },
      {
        id: 'lgmd-r2',
        name: 'LGMD R2 — Disferlinopatia',
        badge: 'Também causa Miopatia de Miyoshi',
        inheritancePattern: 'Autossômica recessiva',
        affectedGene: 'Gene DYSF (cromossomo 2)',
        severity: 'moderada',
        description: 'Causada por variantes no gene da disferlina. Pode se apresentar como LGMD (fraqueza proximal) ou como Miopatia de Miyoshi (fraqueza distal na panturrilha).',
        details: 'A variabilidade clínica é notável — irmãos com a mesma mutação podem ter fenótipos completamente diferentes (um com LGMD, outro com Miopatia de Miyoshi). A CK é geralmente muito elevada. O início costuma ser entre 15 e 35 anos.',
        symptoms: ['Fraqueza proximal (LGMD2B) ou distal posterior (Miyoshi)', 'CK extremamente elevada (>10x o normal)', 'Início na adolescência ou vida adulta jovem', 'Dificuldade de levantar dos calcanhares (Miyoshi)'],
        care: 'Fisioterapia adaptada ao fenótipo. Corticoides não demonstraram eficácia consistente. Ensaios de terapia baseada em membrana em andamento.',
      },
      {
        id: 'lgmd-r3',
        name: 'LGMD R3 — α-Sarcoglicanopatia',
        badge: 'Forma grave — Duchenne-like',
        inheritancePattern: 'Autossômica recessiva',
        affectedGene: 'Gene SGCA (cromossomo 17)',
        severity: 'grave',
        description: 'Uma das sarcoglicanopatias, pode ser tão grave quanto a DMD em termos de velocidade de progressão e perda da marcha.',
        details: 'O complexo de sarcoglicanos (α, β, γ, δ) ancora a distrofina à membrana da célula muscular. A ausência de qualquer um deles desestabiliza toda a estrutura. A LGMD R3 e R5 tendem a ser as formas mais graves deste grupo.',
        symptoms: ['Fraqueza muscular proximal de início na infância ou adolescência', 'Hipertrofia de panturrilhas (como na DMD)', 'Comprometimento cardíaco em alguns casos', 'Escoliose e contraturas'],
        care: 'Corticoterapia (benefício similar à DMD), fisioterapia, cardiologia. Terapia gênica com vetor AAV em ensaios clínicos.',
      },
      {
        id: 'lgmd-r4',
        name: 'LGMD R4 — β-Sarcoglicanopatia',
        badge: 'Sarcoglicanopatia',
        inheritancePattern: 'Autossômica recessiva',
        affectedGene: 'Gene SGCB (cromossomo 4)',
        severity: 'variável',
        description: 'Variante de sarcoglicanopatia com fenótipo variável, desde formas graves com perda precoce da marcha até formas mais brandas de progressão lenta.',
        details: 'Clinicamente indistinguível de outras sarcoglicanopatias sem teste genético. O painel de sarcoglicanos por imunohistoquímica em biópsia muscular pode orientar qual gene testar primeiro.',
        symptoms: ['Fraqueza proximal progressiva', 'Elevação de CK', 'Variabilidade clínica mesmo entre irmãos'],
        care: 'Corticoterapia, fisioterapia e acompanhamento multidisciplinar. O benefício dos corticoides é menor que na DMD, mas pode haver estabilização.',
      },
      {
        id: 'lgmd-r5',
        name: 'LGMD R5 — γ-Sarcoglicanopatia',
        badge: 'Forma mais grave das sarcoglicanopatias',
        inheritancePattern: 'Autossômica recessiva',
        affectedGene: 'Gene SGCG (cromossomo 13)',
        severity: 'grave',
        description: 'Junto com a LGMD R3, é a forma mais grave entre as sarcoglicanopatias. Progressão pode se assemelhar à Duchenne.',
        details: 'Frequentemente descrita em populações de origem gipsiana (Roma) por efeito fundador. Mas ocorre em todas as populações. O comprometimento cardíaco é relevante e requer monitoramento regular.',
        symptoms: ['Início na infância (3–15 anos)', 'Perda da marcha antes dos 20 anos em casos graves', 'Comprometimento respiratório e cardíaco'],
        care: 'Corticoterapia, fisioterapia respiratória, cardiologia. Terapia gênica AAV em ensaios clínicos ativos para γ-sarcoglicano.',
      },
      {
        id: 'lgmd-r6',
        name: 'LGMD R6 — δ-Sarcoglicanopatia',
        badge: 'Sarcoglicanopatia',
        inheritancePattern: 'Autossômica recessiva',
        affectedGene: 'Gene SGCD (cromossomo 5)',
        severity: 'variável',
        description: 'A menos frequente entre as sarcoglicanopatias. Pode associar-se a cardiomiopatia dilatada mesmo com fraqueza muscular leve.',
        details: 'O principal alerta clínico na LGMD R6 é o risco de cardiomiopatia desproporcional à fraqueza muscular — o monitoramento cardíaco é prioritário independentemente do estado funcional motor do paciente.',
        symptoms: ['Fraqueza proximal de gravidade variável', 'Cardiomiopatia dilatada (pode ser predominante)', 'CK elevada'],
        care: 'Cardiologia com ecocardiograma periódico (mesmo assintomático), IECAs/betabloqueadores se cardiomiopatia presente, fisioterapia.',
      },
      {
        id: 'lgmd-r9',
        name: 'LGMD R9 — FKRP-relacionada',
        badge: 'Forma frequente em populações europeias',
        inheritancePattern: 'Autossômica recessiva',
        affectedGene: 'Gene FKRP (cromossomo 19)',
        severity: 'variável',
        description: 'Causada por variantes no gene FKRP (fukutina-related protein). A variante p.Leu276Ile é especialmente comum em populações europeias. O espectro vai de formas brandas a formas com gravidade similar à DMD.',
        details: 'Formas graves de LGMD R9 com variantes bialélicas severas podem se apresentar como uma distroglicanopatia (MDC1C) com início na infância e comprometimento cerebral. Formas mais brandas têm início tardio e progressão lenta. O gene FKRP é um alvo de terapia gênica atualmente em ensaios de fase 2.',
        symptoms: ['Fraqueza proximal variável', 'Hipertrofia de panturrilhas (em alguns casos)', 'Comprometimento cardíaco em formas mais graves', 'CK bastante elevada'],
        care: 'Fisioterapia, cardiologia, pneumologia. Terapia gênica AAV com gene FKRP em estudo clínico fase 2 (Myonexus/Sarepta).',
      },
      {
        id: 'lgmd-r12',
        name: 'LGMD R12 — Anoctaminopatia (ANO5)',
        badge: 'Frequente na Europa — subdiagnosticada',
        inheritancePattern: 'Autossômica recessiva',
        affectedGene: 'Gene ANO5 (cromossomo 11)',
        severity: 'moderada',
        description: 'Causada por variantes no gene ANO5 (anoctamina 5). É uma das LGMD mais frequentes na Europa e possivelmente subdiagnosticada no Brasil. Pode se apresentar como forma LGMD ou distal.',
        details: 'A variante c.191dupA é especialmente prevalente em populações do norte da Europa. Homens tendem a ser mais afetados que mulheres. A progressão é geralmente lenta. Atrofia assimétrica das panturrilhas é frequente.',
        symptoms: ['Fraqueza proximal lentamente progressiva', 'Atrofia assimétrica das panturrilhas', 'CK muito elevada (pode ser o primeiro achado)', 'Dificuldade para correr e subir escadas'],
        care: 'Fisioterapia. Atualmente sem terapia específica aprovada; pesquisas em andamento.',
      },
      {
        id: 'lgmd-d1',
        name: 'LGMD D1 — Miotilinopatia',
        badge: 'Forma dominante — início tardio',
        inheritancePattern: 'Autossômica dominante',
        affectedGene: 'Gene MYOT (cromossomo 5)',
        severity: 'variável',
        description: 'Uma das formas dominantes de LGMD, com início geralmente na vida adulta (40–60 anos). Pode também se apresentar como miopatia distal (miopatia distal de Laing-like).',
        details: 'As formas dominantes de LGMD (grupo D) tendem a ter início mais tardio e progressão mais lenta que as formas recessivas. A Miotilinopatia pode se associar a neuropatia periférica.',
        symptoms: ['Fraqueza proximal de início tardio (adulto)', 'Progressão lenta', 'Eventual comprometimento distal', 'Neuropatia associada em alguns casos'],
        care: 'Fisioterapia adaptada à idade e ao fenótipo. Avaliação neurológica para neuropatia associada.',
      },
    ],
  },

  {
    id: 'emery-dreifuss',
    name: 'Emery-Dreifuss (EDMD)',
    badge: 'Alto risco de morte súbita cardíaca',
    frequencyRank: 2,
    frequencyLabel: '1 em cada 100.000 a 300.000 pessoas',
    inheritancePattern: 'Ligada ao X, autossômica dominante ou recessiva',
    affectedGene: 'EMD (emerina), LMNA (laminina A/C), FHL1, SYNE1/2 entre outros',
    description: 'Caracterizada pela tríade clássica: contraturas precoces nas articulações, fraqueza muscular lentamente progressiva e comprometimento cardíaco grave com risco de morte súbita.',
    details: 'O risco cardíaco pode anteceder completamente a fraqueza muscular. Parentes assintomáticos de pacientes com EDMD ligada ao gene LMNA também devem ser avaliados cardiologicamente.',
    symptoms: [
      'Rigidez articular precoce no pescoço, cotovelos e tornozelos (antes da fraqueza)',
      'Fraqueza muscular de progressão lenta (húmero-peroneal)',
      'Palpitações, síncope ou pré-síncope (sinal de alarme)',
      'Bloqueios cardíacos e arritmias graves',
    ],
    care: 'Monitoramento cardíaco contínuo com ECG e Holter, implante precoce de marcapasso ou CDI conforme indicação. Fisioterapia para contraturas.',
    hasSubtypes: false,
  },

  {
    id: 'oculofaringea',
    name: 'Oculofaríngea (OPMD)',
    badge: 'Início tardio — 5ª–6ª décadas',
    frequencyRank: 2,
    frequencyLabel: '1 em cada 100.000 (mais prevalente em Quebec e Israel)',
    inheritancePattern: 'Autossômica dominante (geralmente)',
    affectedGene: 'Gene PABPN1 (cromossomo 14) — expansão de repetições GCG',
    description: 'Distrofia de início tardio (geralmente após os 50 anos) que afeta primeiramente os músculos dos olhos e da garganta, causando ptose palpebral progressiva e disfagia.',
    details: 'A progressão é lenta e muitos portadores vivem décadas com boa qualidade de vida. A disfagia (dificuldade de deglutição) é a complicação mais séria e pode levar a pneumonias aspirativas. O tratamento cirúrgico melhora significativamente a qualidade de vida.',
    symptoms: [
      'Ptose palpebral progressiva (queda das pálpebras)',
      'Disfagia (dificuldade para engolir sólidos e líquidos)',
      'Disartria (dificuldade de falar claramente)',
      'Fraqueza proximal nos membros em estágios avançados',
    ],
    care: 'Cirurgia de ptose palpebral, miotomia cricofaríngea ou dilatação para disfagia, fonoterapia, fisioterapia. Acompanhamento nutricional.',
    hasSubtypes: false,
  },

  {
    id: 'distais',
    name: 'Distrofias Distais',
    badge: 'Grupo com várias formas distintas',
    frequencyRank: 2,
    frequencyLabel: 'Variável — algumas formas mais prevalentes na Escandinávia',
    inheritancePattern: 'Autossômica dominante ou recessiva (varia por subtipo)',
    affectedGene: 'MYH7, DYSF, ANO5, MATR3, VCP, GNE, TTN entre outros',
    description: 'Grupo de distrofias que afeta primeiramente as extremidades (mãos, pés, antebraços e pernas distais), ao contrário das formas que começam na cintura.',
    details: 'Cada subtipo tem padrão de envolvimento muscular e progressão distintos. O diagnóstico diferencial é feito por painel genético.',
    symptoms: [
      'Fraqueza e atrofia nas mãos, pés, antebraços ou panturrilhas (dependendo do subtipo)',
      'Dificuldade para abrir potes, digitar ou fazer atividades finas',
      'Pé caído em alguns subtipos',
      'Progressão ascendente para músculos proximais em casos avançados',
    ],
    care: 'Órteses para pé caído, fisioterapia, adaptações ergonômicas. GNE-miopatia tem ensaios clínicos em andamento.',
    hasSubtypes: true,
    subtypes: [
      {
        id: 'welander',
        name: 'Miopatia Distal de Welander',
        badge: 'Início nos dedos e punhos',
        inheritancePattern: 'Autossômica dominante',
        affectedGene: 'Gene TIA1 (cromossomo 2)',
        severity: 'leve',
        description: 'Forma de início tardio (geralmente após os 40 anos) que começa nos dedos indicadores e se espalha lentamente para as mãos e, depois, para os pés. Particularmente prevalente na Suécia.',
        details: 'A miopatia de Welander progride muito lentamente. A maioria dos pacientes mantém a capacidade de caminhar por décadas. O comprometimento começa nos extensores dos dedos (dificuldade de levantar os dedos), diferente de outras miopatias distais que afetam a panturrilha.',
        symptoms: ['Dificuldade de levantar os dedos indicadores', 'Fraqueza progressiva nas mãos', 'Atrofia dos extensores dos dedos', 'Pé caído em estágios tardios'],
        care: 'Órteses para mão e pé se necessário, terapia ocupacional, fisioterapia de manutenção.',
      },
      {
        id: 'miyoshi',
        name: 'Miopatia de Miyoshi (Disferlinopatia Distal)',
        badge: 'Início na panturrilha posterior',
        inheritancePattern: 'Autossômica recessiva',
        affectedGene: 'Gene DYSF (cromossomo 2) — mesmo gene da LGMD R2',
        severity: 'moderada',
        description: 'Forma distal da disferlinopatia. Começa nos músculos posteriores da perna (gastrocnêmio/sóleo), causando dificuldade de levantar nos calcanhares, diferente da maioria das miopatias distais.',
        details: 'A Miopatia de Miyoshi é clinicamente reconhecida pelo início característico na musculatura posterior da perna — os pacientes não conseguem levantar nos calcanhares. A CK é extremamente elevada (frequentemente >10x o normal) e pode ser o primeiro sinal encontrado em exame de rotina.',
        symptoms: ['Dificuldade de levantar nos calcanhares (sinal mais característico)', 'Atrofia da panturrilha posterior', 'CK extremamente elevada', 'Progressão para quadris e coxas em anos'],
        care: 'Fisioterapia adaptada, órteses para pé caído, avaliação genética para confirmar variante DYSF.',
      },
      {
        id: 'nonaka-gne',
        name: 'Miopatia de Nonaka / GNE-miopatia',
        badge: 'Rara — ensaios ativos',
        inheritancePattern: 'Autossômica recessiva',
        affectedGene: 'Gene GNE (cromossomo 9)',
        severity: 'moderada',
        description: 'Forma distal que começa nos músculos anteriores da perna (tibial anterior), poupando classicamente os músculos do quadríceps (característica diagnóstica importante). Mais prevalente em japoneses, iranianos e judeus.',
        details: 'A GNE-miopatia (nome atual recomendado) tem uma característica clínica muito específica: a preservação relativa do quadríceps mesmo em estágios avançados, quando os outros músculos da coxa já estão gravemente comprometidos. Isso a diferencia clinicamente de outras miopatias distais. Estudos clínicos de suplementação de ManNAc e acido siálico foram conduzidos com resultados mistos.',
        symptoms: ['Fraqueza e atrofia dos músculos da perna anterior (tibial anterior)', 'Pé caído precoce', 'Preservação do quadríceps (sinal diagnóstico importante)', 'Progressão para braços e ombros em décadas'],
        care: 'Órteses para pé caído, fisioterapia. Ensaios clínicos de suplementação de ácido siálico (Ultragenyx) em investigação.',
      },
      {
        id: 'laing',
        name: 'Miopatia Distal de Laing',
        badge: 'Início na dorsiflexão do pé',
        inheritancePattern: 'Autossômica dominante',
        affectedGene: 'Gene MYH7 (cromossomo 14) — miosina de cadeia pesada tipo β',
        severity: 'leve',
        description: 'Forma dominante com início nos músculos do pescoço, pés (dorsiflexores) e dedos grandes. Progressão é lenta e a maioria mantém a marcha por décadas.',
        details: 'O mesmo gene MYH7 causa a cardiomiopatia hipertrófica e a miopatia distal de Laing, mas variantes diferentes. Dificuldade para levantar o pé (pé caído) e para levantar o polegar são sinais precoces característicos.',
        symptoms: ['Pé caído (dificuldade de levantar o pé ao caminhar)', 'Fraqueza no pescoço (dificuldade de levantar a cabeça deitado)', 'Fraqueza no polegar e dedos', 'Progressão lenta para outros grupos musculares'],
        care: 'Órteses para pé caído, fisioterapia, avaliação cardiológica (pelo gene MYH7).',
      },
      {
        id: 'udd',
        name: 'Miopatia Tibial de Udd (TMD)',
        badge: 'Prevalente na Finlândia',
        inheritancePattern: 'Autossômica dominante',
        affectedGene: 'Gene TTN (cromossomo 2) — titina',
        severity: 'leve',
        description: 'Forma benigna de miopatia distal com início nos músculos tibiais anteriores após os 35 anos. Muito prevalente na Finlândia. Raramente causa incapacidade grave.',
        details: 'O gene TTN (titina) é o maior gene humano. Variantes em diferentes regiões do TTN causam doenças diferentes — formas dominantes distais (TMD), formas recessivas com comprometimento cardíaco grave (LGMD R10 / cardiomiopatia) e formas com comprometimento de membros. O diagnóstico requer sequenciamento específico de TTN.',
        symptoms: ['Fraqueza nos tibiais anteriores após os 35 anos', 'Pé caído unilateral ou bilateral, leve', 'Progressão muito lenta', 'Raramente necessita de cadeira de rodas'],
        care: 'Fisioterapia e órteses leves. Acompanhamento cardiológico preventivo.',
      },
    ],
  },

  {
    id: 'congenita',
    name: 'Distrofias Musculares Congênitas (DMC)',
    badge: 'Manifesta ao nascimento',
    frequencyRank: 2,
    frequencyLabel: 'Grupo raro — mais de 30 subtipos genéticos',
    inheritancePattern: 'Geralmente autossômica recessiva',
    affectedGene: 'LAMA2, COL6A1/2/3, FKTN, POMT1/2, LARGE1, ITGA7 entre outros',
    description: 'Grupo diverso de distrofias que se manifestam desde o nascimento ou nos primeiros meses de vida, com hipotonia ("bebê flácido") e comprometimento motor precoce.',
    details: 'Algumas formas também comprometem o sistema nervoso central. O diagnóstico por painel genético é essencial para definir prognóstico, tratamento e aconselhamento genético.',
    symptoms: [
      'Hipotonia neonatal intensa ("bebê flácido" ao nascer)',
      'Dificuldade de sucção e deglutição no período neonatal',
      'Contraturas articulares (artrogripose)',
      'Atraso ou ausência dos marcos motores',
      'Comprometimento cerebral em alguns subtipos',
    ],
    care: 'Painel genético de sequenciamento amplo (WES ou WGS), suporte nutricional, fisioterapia precoce, suporte respiratório e abordagem multidisciplinar.',
    hasSubtypes: true,
    subtypes: [
      {
        id: 'mdc1a',
        name: 'DMC com Deficiência de Merosina (MDC1A)',
        badge: 'Mais comum entre as DMCs',
        inheritancePattern: 'Autossômica recessiva',
        affectedGene: 'Gene LAMA2 (cromossomo 6) — laminina α2 (merosina)',
        severity: 'grave',
        description: 'A forma mais frequente de DMC em muitas populações. Causada pela ausência ou deficiência da proteína merosina (laminina α2), que ancora as fibras musculares à membrana basal.',
        details: 'A MDC1A causa hipotonia grave ao nascer e a maioria das crianças não adquire marcha independente. O envolvimento do sistema nervoso central (leucodistrofia nas neuroimagens) é frequente, mas a inteligência costuma ser normal. Comprometimento respiratório precoce requer atenção.',
        symptoms: ['Hipotonia grave ao nascer', 'Não alcança marcha independente na maioria dos casos', 'Leucodistrofia (alteração na substância branca do cérebro na RM)', 'Insuficiência respiratória precoce', 'Convulsões em uma minoria'],
        care: 'Ventilação não invasiva precoce, fisioterapia respiratória e motora, suporte nutricional, anticonvulsivante se necessário. Pesquisa de terapias com laminin-111.',
      },
      {
        id: 'ullrich',
        name: 'DMC de Ullrich (UCMD)',
        badge: 'Hipotonia + hiperflexibilidade distal',
        inheritancePattern: 'Autossômica recessiva (maioria) ou dominante de novo',
        affectedGene: 'Genes COL6A1, COL6A2 ou COL6A3 (cromossomo 21 e 2)',
        severity: 'grave',
        description: 'Forma de DMC causada por deficiência do colágeno VI. Apresenta a combinação paradoxal de contraturas proximais com hiperflexibilidade (hipermobilidade) nas articulações distais.',
        details: 'A combinação de rigidez nos quadris, joelhos e cotovelos com hipermobilidade nos tornozelos e punhos é um marcador clínico muito característico da UCMD. A insuficiência respiratória é progressiva e geralmente precede qualquer comprometimento motor grave. A forma de Bethlem (alélica) é mais branda.',
        symptoms: ['Hipotonia neonatal com dificuldade de sugar', 'Contraturas nos quadris, joelhos e cotovelos', 'Hipermobilidade nos punhos, dedos e tornozelos (paradoxal)', 'Fraqueza muscular progressiva', 'Insuficiência respiratória — frequentemente antes dos 10 anos'],
        care: 'Ventilação não invasiva noturna precoce e, depois, 24h se necessário. Fisioterapia intensiva para minimizar contraturas. Pesquisa de terapia com rapamicina (mTOR).',
      },
      {
        id: 'bethlem',
        name: 'Miopatia de Bethlem',
        badge: 'Forma mais branda da Colagenopatia VI',
        inheritancePattern: 'Autossômica dominante (maioria)',
        affectedGene: 'Genes COL6A1, COL6A2 ou COL6A3',
        severity: 'leve',
        description: 'A forma mais branda das colagenopatias de colágeno VI. Inicio pode ser na infância ou na vida adulta. A maioria mantém a marcha por décadas.',
        details: 'A Miopatia de Bethlem se distingue da UCMD pela maior leveza. Contraturas no pescoço, cotovelos e tornozelos são comuns. A insuficiência respiratória ocorre tardiamente e em menor proporção. Pode ser confundida com outras miopatias brandas.',
        symptoms: ['Fraqueza muscular lentamente progressiva', 'Contraturas nos cotovelos, tornozelos e pescoço', 'Pele levemente espessada ou com queloides (relacionado ao colágeno)', 'Progressão lenta — marcha mantida até a meia-idade em muitos casos'],
        care: 'Fisioterapia para contraturas, órteses, monitoramento respiratório a partir da 4ª–5ª décadas.',
      },
      {
        id: 'fukuyama',
        name: 'DMC de Fukuyama (FCMD)',
        badge: 'Mais prevalente no Japão',
        inheritancePattern: 'Autossômica recessiva',
        affectedGene: 'Gene FKTN (cromossomo 9) — fukutina',
        severity: 'grave',
        description: 'Uma das formas mais graves de DMC, com comprometimento muscular E cerebral graves. É a 2ª DMC mais comum no Japão (após DMD), mas rara em outras populações.',
        details: 'A fukutina é necessária para a glicosilação da α-distroglicana. A sua ausência causa distrofia muscular com lisencefalia (córtex cerebral malformado), comprometimento visual, epilepsia e deficiência intelectual grave. A maioria das crianças afetadas não anda e tem expectativa de vida reduzida.',
        symptoms: ['Hipotonia grave ao nascer', 'Malformação cortical (paquigiria/polimicrogiria) na RM', 'Convulsões', 'Deficiência intelectual grave', 'Oftalmoplegia e miopia em muitos casos'],
        care: 'Suporte multidisciplinar intensivo: anticonvulsivante, ventilação, nutrição enteral, fisioterapia, oftalmologia. Cuidados paliativos quando indicado.',
      },
      {
        id: 'walker-warburg',
        name: 'Síndrome de Walker-Warburg (WWS)',
        badge: 'Forma mais grave das DMCs',
        inheritancePattern: 'Autossômica recessiva',
        affectedGene: 'POMT1, POMT2, POMGNT1, FKTN, FKRP, LARGE1 entre outros',
        severity: 'grave',
        description: 'A forma mais grave de DMC, com malformações cerebrais e oculares graves associadas à distrofia muscular. A expectativa de vida raramente ultrapassa 3 anos.',
        details: 'A WWS é causada por defeitos na O-manosila­ção da α-distroglicana (distroglicanopatia grave). O quadro é de lisencefalia grave, hidrocefalia, malformação de Dandy-Walker, anormalidades oculares severas (microftalmia, coloboma, catarata) e distrofia muscular grave. O diagnóstico pode ser suspeitado na ultrassonografia pré-natal.',
        symptoms: ['Hipotonia profunda ao nascer', 'Malformações cerebrais graves (lisencefalia, hidrocefalia)', 'Anormalidades oculares graves (microftalmia, catarata congênita)', 'Crises epilépticas refratárias', 'Apneia e insuficiência respiratória precoce'],
        care: 'Cuidados paliativos e suporte intensivo. Anticonvulsivantes, gastrostomia para nutrição, suporte ventilatório. Acompanhamento multidisciplinar com discussão ética sobre intensidade do suporte.',
      },
      {
        id: 'mdc1c',
        name: 'DMC tipo 1C (MDC1C) — FKRP Congênita',
        badge: 'Forma congênita da FKRP-relacionada',
        inheritancePattern: 'Autossômica recessiva',
        affectedGene: 'Gene FKRP (cromossomo 19) — forma grave',
        severity: 'grave',
        description: 'Variantes bialélicas mais severas no gene FKRP causam não apenas a forma LGMD R9 (mais branda), mas também uma forma congênita grave com início ao nascer e possível comprometimento cerebral.',
        details: 'A MDC1C representa o extremo grave do espectro FKRP. As crianças apresentam hipotonia grave ao nascer, não alcançam marcha e podem ter comprometimento cerebral (estrutural ou intelectual). O mesmo gene FKRP, com variantes diferentes, causa a muito mais branda LGMD R9.',
        symptoms: ['Hipotonia grave ao nascer', 'Não alcança marcha independente', 'Comprometimento cerebral (variável)', 'Insuficiência respiratória precoce', 'CK muito elevada'],
        care: 'Suporte ventilatório precoce, fisioterapia, nutrição. Terapia gênica com gene FKRP em estudo clínico fase 2 (pode incluir formas graves no futuro).',
      },
    ],
  },
];

// Helper: busca condição por slug/id
export function getConditionById(id: string): Condition | undefined {
  return conditions.find((c) => c.id === id);
}

// Helper: só condições com subtipos
export function getConditionsWithSubtypes(): Condition[] {
  return conditions.filter((c) => c.hasSubtypes);
}
